dist: bionic

language: go

go_import_path: github.com/ontio/ontology

os:
  - linux
  - osx
  - windows

go:
  - 1.12.x

script:
  - env GO111MODULE=on make all
  - env GO111MODULE=on go mod vendor
  - cd ./wasmtest && bash ./run-wasm-tests.sh && cd ../
  - bash ./.travis.check-license.sh
  - bash ./.travis.gofmt.sh
  - bash ./.travis.gotest.sh
