dist: bionic

language: go

go_import_path: github.com/ontio/ontology

os:
  - linux
  - osx

go:
  - 1.12.x

script:
  - env GO111MODULE=on make all
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; env GO111MODULE=on go mod vendor; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; cd ./wasmtest && bash ./run-wasm-tests.sh && cd ../; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; bash ./.travis.check-license.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; bash ./.travis.gofmt.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; bash ./.travis.gotest.sh; fi
