dist: bionic

language: go

go_import_path: github.com/ontio/ontology

os:
  - linux
  - osx
  - windows

go:
  - 1.12.x

matrix:
    exclude:
        - os: linux
        - os: osx
        - os: windows
    include:
        - language: rust
          rust: nightly
          os: linux
          script:
            - ./.travis.script.bash
        - language: rust
          rust: nightly
          os: windows
          script:
            - ./.travis.script.bash
        - language: rust
          rust: nightly
          os: osx
          script:
            - ./.travis.script.bash
